# Generated by Django 5.1.6 on 2025-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
